### PR TITLE
V1.3.0

### PR DESCRIPTION
**Pull request by spaul91**
`-icoverage per chromosome` argument added to app UI

Test command (note: `-iper_chromosome_coverage=true` omitted from test run where plots not required)

```
dx run app-eggd_athena -iexons_nirvana="project-Fkb6Gkj433GVVvj73J7x8KbV:file-Fq18Yp0433GjB7172630p9Yv" -ipanel_bed="project-Fkb6Gkj433GVVvj73J7x8KbV:file-G4F6jX04ZFVV3JZJG62ZQ5yJ" -isummary=true -ithresholds="50,100,150,250" -icutoff_threshold="100" -imosdepth_files="002_211015_A01303_0033_AHLGJVDRXY_TSO500:/output/helios_v1.2.0_211017-1/eggd_mosdepth_v1.0.1/GM2110198-1-227717-DNA-egg6.per-base.bed.gz" -imosdepth_files="002_211015_A01303_0033_AHLGJVDRXY_TSO500:/output/helios_v1.2.0_211017-1/eggd_mosdepth_v1.0.1/GM2110198-1-227717-DNA-egg6.reference_build.txt" -iname=${SAMPLE_PREFIX} --destination "003_sophie_paul_workspace:test_athena_with_cov" -iper_chromosome_coverage=true -y
```

Test output:

- with per-chromosome plots: https://dl.ec1.dnanex.us/F/D/bg0Fj3q82GZqBJKZ9K03z24g0vB4yKJ3Z0GbKQKf?inline&dxDomain=https://platform.dnanexus.com
- without per-chromosome plots: https://dl.ec1.dnanex.us/F/D/qPkGyKXjVYJXQfgf4fvkGbFBzK8Gzbz76421GjxG?inline&dxDomain=https://platform.dnanexus.com

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_athena/16)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
those download urls expire after 24 hours, could you link the jobs here please to take a look

> Reviewed 3 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_athena/16#-:-Mq_-pfp5YZShdzNmTQy:bxa07a3)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @jethror1 and @spaul91)

___
*[dxapp.json, line 2 at r1](https://reviewable.io/reviews/eastgenomics/eggd_athena/16#-Mq_0AxyBafOAgjP3UXx:-Mq_0AxzEarJCocEtPMK:b-8v0oje) ([raw file](https://github.com/eastgenomics/eggd_athena/blob/cb2cc7396b51bc2a4a9e7b01cc1cec2d981567b9/dxapp.json#L2)):*
> ```JSON
> {
>   "name": "eggd_athena",
> ```

if this is switching to an app and not applet it will need a version tag: https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/78ed75253c0b55a0dd38db9e7d555fec44d82dcb/dxapp.json#L10

**Review by spaul91 — COMMENTED** [review]
Sorry!

- with extra plots: https://platform.dnanexus.com/panx/project-G6Pkb384qPGBfY9P6B33Qgxx/file-G6g2jX04x122b9Fk9VfXK0vp/view?viewer=true
- without extra plots: https://platform.dnanexus.com/panx/project-G6Pkb384qPGBfY9P6B33Qgxx/file-G6g0jz04v6B67567B5zYBZ26/view?viewer=true

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_athena/16#-:-Mq_206bC2Vv2pxa4vLu:bcwwlfj)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[dxapp.json, line 2 at r1](https://reviewable.io/reviews/eastgenomics/eggd_athena/16#-Mq_0AxyBafOAgjP3UXx:-Mq_2GR82yOsKVd9Pugs:b9gjqyb) ([raw file](https://github.com/eastgenomics/eggd_athena/blob/cb2cc7396b51bc2a4a9e7b01cc1cec2d981567b9/dxapp.json#L2)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

if this is switching to an app and not applet it will need a version tag: https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/78ed75253c0b55a0dd38db9e7d555fec44d82dcb/dxapp.json#L10
</blockquote></details>

Updated, thanks

**Review by spaul91 — COMMENTED** [review]
Links to output directories:

- https://platform.dnanexus.com/panx/projects/G6Pkb384qPGBfY9P6B33Qgxx/data/test_athena_with_cov/
- https://platform.dnanexus.com/panx/projects/G6Pkb384qPGBfY9P6B33Qgxx/data/test_athena_without_cov/

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_athena/16#-:-Mq_2jXc6aL2O0Z4T2Ah:buj9h21)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @jethror1)

**Review by jethror1 — COMMENTED** [review]
looks good, thanks for this

> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_athena/16#-:-Mq_5rFk65M08bRjweP-:b-73ovpy)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @jethror1)

**Review by jethror1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_athena/16#-:-Mq_5vw27MEsGDmztl4w:bnfp4nl)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @jethror1)

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_athena/16)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spaul91)

**Pull request merged**
