### PR TITLE
initial release

### PR DESCRIPTION
**Pull request by jethror1**
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_athena/1)

### CODE REVIEW

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 1 of 26 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_athena/1)* status: 1 of 26 files reviewed, 3 unresolved discussions (waiting on @jethror1 and @mattgarner)

___
*[dxapp.json, line 5 at r1](https://reviewable.io/reviews/eastgenomics/eggd_athena/1#-MJl5HvZDE3JqiETiEzR:-MJl5HvZDE3JqiETiEzS:b8g5nud) ([raw file](https://github.com/eastgenomics/eggd_athena/blob/ead5ac196948bd24fc2c6a2363948d729143f070/dxapp.json#L5)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>   "name": "eggd_athena_v1.0.0",
>   "title": "eggd_athena_v1.0.0",
>   "summary": "DNAnexus app of Athena",
>   "dxapi": "1.0.0",
>   "properties": {
>     "githubRelease": "v1.0.1"
> ```
</details>

Versions mismatch 1.0.0 vs 1.0.1
___
*[dxapp.json, line 42 at r1](https://reviewable.io/reviews/eastgenomics/eggd_athena/1#-MJl7AD93RsgVQ7Kopp7:-MJl7AD93RsgVQ7Kopp8:b-yzb8jt) ([raw file](https://github.com/eastgenomics/eggd_athena/blob/ead5ac196948bd24fc2c6a2363948d729143f070/dxapp.json#L42)):*
> ```JSON
>       "optional": false,
>       "patterns": [
>         "*"
> ```

*.bed ?
___
*[dxapp.json, line 100 at r1](https://reviewable.io/reviews/eastgenomics/eggd_athena/1#-MJl8M4QBWJ2xLes18u9:-MJl8M4QBWJ2xLes18uA:b-yocl69) ([raw file](https://github.com/eastgenomics/eggd_athena/blob/ead5ac196948bd24fc2c6a2363948d729143f070/dxapp.json#L100)):*
> ```JSON
>       "optional": true,
>       "patterns": [
>         "*"
> ```

*.vcf ?

**Review by mattgarner — COMMENTED** [review]
> Reviewed 3 of 26 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_athena/1)* status: 4 of 26 files reviewed, 3 unresolved discussions (waiting on @jethror1 and @mattgarner)

**Review by mattgarner — COMMENTED** [review]
> Reviewed 2 of 26 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_athena/1)* status: 6 of 26 files reviewed, 3 unresolved discussions (waiting on @jethror1 and @mattgarner)

**Review by mattgarner — DISMISSED** [review]
> Reviewed 20 of 26 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_athena/1)* status: all files reviewed, 10 unresolved discussions (waiting on @jethror1)

___
*[src/eggd_athena.sh, line 19 at r1](https://reviewable.io/reviews/eastgenomics/eggd_athena/1#-MJlAjVRBeVviM__KSzK:-MJlAjVRBeVviM__KSzL:b-iyvhz2) ([raw file](https://github.com/eastgenomics/eggd_athena/blob/ead5ac196948bd24fc2c6a2363948d729143f070/src/eggd_athena.sh#L19)):*
> ```Shell
>     # download SNPs if given to SNPs dir
>     mkdir snps && cd snps
>     
> ```

whitespace
___
*[src/eggd_athena.sh, line 41 at r1](https://reviewable.io/reviews/eastgenomics/eggd_athena/1#-MJlKeiaAyJHljGL5vw7:-MJlKeib2I4tNiRWfhO-:b32x0h) ([raw file](https://github.com/eastgenomics/eggd_athena/blob/ead5ac196948bd24fc2c6a2363948d729143f070/src/eggd_athena.sh#L41)):*
> ```Shell
>     unzip athena-*.zip
>     sudo chmod -R 775 athena-*
>     
> ```

ws
___
*[src/eggd_athena.sh, line 53 at r1](https://reviewable.io/reviews/eastgenomics/eggd_athena/1#-MJlLmjn3jhZGloXnJ29:-MJlLmjoBu3zwxiBUmPe:bm17loi) ([raw file](https://github.com/eastgenomics/eggd_athena/blob/ead5ac196948bd24fc2c6a2363948d729143f070/src/eggd_athena.sh#L53)):*
> ```
> athena-development
> ```
I guess this will change when athena is done and you no longer use a dev version
___
*[src/eggd_athena.sh, line 65 at r1](https://reviewable.io/reviews/eastgenomics/eggd_athena/1#-MJlMA63-N3v26awLzCl:-MJlMA63-N3v26awLzCm:b32x0h) ([raw file](https://github.com/eastgenomics/eggd_athena/blob/ead5ac196948bd24fc2c6a2363948d729143f070/src/eggd_athena.sh#L65)):*
> ```Shell
>     if [ "$build_name" ]; then stats_args+=" --build $build_name"; fi
>     if [ "$name" ]; then stats_args+=" --outfile ${name}"; fi
>     
> ```

ws
___
*[src/eggd_athena.sh, line 69 at r1](https://reviewable.io/reviews/eastgenomics/eggd_athena/1#-MJlMB4tA5wNehvDTyPf:-MJlMB4tA5wNehvDTyPg:b32x0h) ([raw file](https://github.com/eastgenomics/eggd_athena/blob/ead5ac196948bd24fc2c6a2363948d729143f070/src/eggd_athena.sh#L69)):*
> ```Shell
>     stats_cmd+=$stats_args
>     echo "Generating coverage stats with: " $stats_cmd
>     
> ```

ws
___
*[src/eggd_athena.sh, line 72 at r1](https://reviewable.io/reviews/eastgenomics/eggd_athena/1#-MJlMBd_1_2uqJlCFz1n:-MJlMBd_1_2uqJlCFz1o:b32x0h) ([raw file](https://github.com/eastgenomics/eggd_athena/blob/ead5ac196948bd24fc2c6a2363948d729143f070/src/eggd_athena.sh#L72)):*
> ```Shell
>     # generate single sample stats
>     time ./miniconda3/bin/python ./athena-development/bin/coverage_stats_single.py $stats_cmd
>         
> ```

ws
___
*[src/eggd_athena.sh, line 94 at r1](https://reviewable.io/reviews/eastgenomics/eggd_athena/1#-MJlMCxu007XWvd8uJfg:-MJlMCxu007XWvd8uJfh:b32x0h) ([raw file](https://github.com/eastgenomics/eggd_athena/blob/ead5ac196948bd24fc2c6a2363948d729143f070/src/eggd_athena.sh#L94)):*
> ```Shell
>     # generate report
>     time ./miniconda3/bin/python $report_cmd
>     
> ```

ws

**Review by Yu-jinKim — CHANGES_REQUESTED** [review]
> Reviewed 6 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_athena/1)* status: all files reviewed, 11 unresolved discussions (waiting on @jethror1)

___
*[dxapp.json, line 6 at r2](https://reviewable.io/reviews/eastgenomics/eggd_athena/1#-MK4QDwc21gEH1hRxS5_:-MK4QDwc21gEH1hRxS5a:bq2wupy) ([raw file](https://github.com/eastgenomics/eggd_athena/blob/a5ff6fb4b3ed8f831f570303711bbb86f5e41e11/dxapp.json#L6)):*
> ```JSON
>   "summary": "DNAnexus app of Athena",
>   "dxapi": "1.0.0",
>   "properties": {
> ```

do you need to add the release of athena?

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_athena/1)* status: 23 of 26 files reviewed, 11 unresolved discussions (waiting on @mattgarner and @Yu-jinKim)

___
*[dxapp.json, line 5 at r1](https://reviewable.io/reviews/eastgenomics/eggd_athena/1#-MJl5HvZDE3JqiETiEzR:-MKAoaT36HZRD_st6yOp:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_athena/blob/ead5ac196948bd24fc2c6a2363948d729143f070/dxapp.json#L5)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
>   "name": "eggd_athena_v1.0.0",
>   "title": "eggd_athena_v1.0.0",
>   "summary": "DNAnexus app of Athena",
>   "dxapi": "1.0.0",
>   "properties": {
>     "githubRelease": "v1.0.1"
> ```
Versions mismatch 1.0.0 vs 1.0.1
</blockquote></details>

Done.
___
*[dxapp.json, line 42 at r1](https://reviewable.io/reviews/eastgenomics/eggd_athena/1#-MJl7AD93RsgVQ7Kopp7:-MKAokTxDm4dTgFGoH-5:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_athena/blob/ead5ac196948bd24fc2c6a2363948d729143f070/dxapp.json#L42)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

*.bed ?
</blockquote></details>

Done.
___
*[dxapp.json, line 100 at r1](https://reviewable.io/reviews/eastgenomics/eggd_athena/1#-MJl8M4QBWJ2xLes18u9:-MKAot-jArud0pGw_PkI:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_athena/blob/ead5ac196948bd24fc2c6a2363948d729143f070/dxapp.json#L100)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

*.vcf ?
</blockquote></details>

Done.
___
*[dxapp.json, line 6 at r2](https://reviewable.io/reviews/eastgenomics/eggd_athena/1#-MK4QDwc21gEH1hRxS5_:-MKAoba-EihLlok9L3Ll:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_athena/blob/a5ff6fb4b3ed8f831f570303711bbb86f5e41e11/dxapp.json#L6)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

do you need to add the release of athena?
</blockquote></details>

Done.
___
*[src/eggd_athena.sh, line 19 at r1](https://reviewable.io/reviews/eastgenomics/eggd_athena/1#-MJlAjVRBeVviM__KSzK:-MKApM8l7OpRYTpCqymP:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_athena/blob/ead5ac196948bd24fc2c6a2363948d729143f070/src/eggd_athena.sh#L19)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

whitespace
</blockquote></details>

Done.
___
*[src/eggd_athena.sh, line 41 at r1](https://reviewable.io/reviews/eastgenomics/eggd_athena/1#-MJlKeiaAyJHljGL5vw7:-MKApJ1K5Uebz5cbbwLH:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_athena/blob/ead5ac196948bd24fc2c6a2363948d729143f070/src/eggd_athena.sh#L41)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

ws
</blockquote></details>

Done.
___
*[src/eggd_athena.sh, line 53 at r1](https://reviewable.io/reviews/eastgenomics/eggd_athena/1#-MJlLmjn3jhZGloXnJ29:-MKApFkm4plAibYix1Hy:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_athena/blob/ead5ac196948bd24fc2c6a2363948d729143f070/src/eggd_athena.sh#L53)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> athena-development
> ```
I guess this will change when athena is done and you no longer use a dev version
</blockquote></details>

Done.
___
*[src/eggd_athena.sh, line 65 at r1](https://reviewable.io/reviews/eastgenomics/eggd_athena/1#-MJlMA63-N3v26awLzCl:-MKApU_q75ucStBYvnhw:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_athena/blob/ead5ac196948bd24fc2c6a2363948d729143f070/src/eggd_athena.sh#L65)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

ws
</blockquote></details>

Done.
___
*[src/eggd_athena.sh, line 69 at r1](https://reviewable.io/reviews/eastgenomics/eggd_athena/1#-MJlMB4tA5wNehvDTyPf:-MKApUzoBpwLPRuiwRzA:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_athena/blob/ead5ac196948bd24fc2c6a2363948d729143f070/src/eggd_athena.sh#L69)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

ws
</blockquote></details>

Done.
___
*[src/eggd_athena.sh, line 72 at r1](https://reviewable.io/reviews/eastgenomics/eggd_athena/1#-MJlMBd_1_2uqJlCFz1n:-MKApVV7Am4z1YJNkZv4:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_athena/blob/ead5ac196948bd24fc2c6a2363948d729143f070/src/eggd_athena.sh#L72)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

ws
</blockquote></details>

Done.
___
*[src/eggd_athena.sh, line 94 at r1](https://reviewable.io/reviews/eastgenomics/eggd_athena/1#-MJlMCxu007XWvd8uJfg:-MKApVvY75Bor3VlkYIR:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_athena/blob/ead5ac196948bd24fc2c6a2363948d729143f070/src/eggd_athena.sh#L94)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

ws
</blockquote></details>

Done.

**Review by Yu-jinKim — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_athena/1)* status: all files reviewed, 12 unresolved discussions (waiting on @jethror1 and @mattgarner)

___
*[src/eggd_athena.sh, line 87 at r2](https://reviewable.io/reviews/eastgenomics/eggd_athena/1#-MKGiZcS6RyiAwi21XzW:-MKGiZcTA7U_RhD-BqaO:bhqnjbe) ([raw file](https://github.com/eastgenomics/eggd_athena/blob/a5ff6fb4b3ed8f831f570303711bbb86f5e41e11/src/eggd_athena.sh#L87)):*
> ```Shell
>     
>     # generate single sample stats
>     time ./miniconda3/bin/python ./$athena_dir/bin/coverage_stats_single.py $stats_cmd
> ```

do you need the time?
___
*[src/eggd_athena.sh, line 109 at r2](https://reviewable.io/reviews/eastgenomics/eggd_athena/1#-MKGikhA83HXc8YkpKzo:-MKGikhA83HXc8YkpKzp:bdk7eh) ([raw file](https://github.com/eastgenomics/eggd_athena/blob/a5ff6fb4b3ed8f831f570303711bbb86f5e41e11/src/eggd_athena.sh#L109)):*
> ```Shell
> 
>     # generapythonte report
>     time ./miniconda3/bin/python $report_cmd
> ```

do you need time?

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_athena/1)* status: all files reviewed, 12 unresolved discussions (waiting on @mattgarner and @Yu-jinKim)

___
*[src/eggd_athena.sh, line 87 at r2](https://reviewable.io/reviews/eastgenomics/eggd_athena/1#-MKGiZcS6RyiAwi21XzW:-MKGu6Is3Yy98g_yuPwn:b16b42a) ([raw file](https://github.com/eastgenomics/eggd_athena/blob/a5ff6fb4b3ed8f831f570303711bbb86f5e41e11/src/eggd_athena.sh#L87)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

do you need the time?
</blockquote></details>

it was useful to see how long each part is taking since the app wraps everything (i.e if including report generation has taken too long as there is too many genes) and just adds some more verbosity to the run, can remove it if you think it shouldn't be left in? 
___
*[src/eggd_athena.sh, line 109 at r2](https://reviewable.io/reviews/eastgenomics/eggd_athena/1#-MKGikhA83HXc8YkpKzo:-MKGuLUI4r6kifS7XpN_:bnj7hl0) ([raw file](https://github.com/eastgenomics/eggd_athena/blob/a5ff6fb4b3ed8f831f570303711bbb86f5e41e11/src/eggd_athena.sh#L109)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

do you need time?
</blockquote></details>

same as above

**Review by Yu-jinKim — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_athena/1)* status: all files reviewed, 10 unresolved discussions (waiting on @mattgarner)

**Review by Yu-jinKim — APPROVED** [review]
> Reviewed 19 of 26 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_athena/1)* status: all files reviewed, 10 unresolved discussions (waiting on @mattgarner)

**Review by Yu-jinKim — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_athena/1)* status: all files reviewed, 10 unresolved discussions (waiting on @mattgarner)

**Review by Yu-jinKim — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_athena/1)* status: all files reviewed, 10 unresolved discussions (waiting on @mattgarner)

___
*[dxapp.json, line 5 at r1](https://reviewable.io/reviews/eastgenomics/eggd_athena/1#-MJl5HvZDE3JqiETiEzR:-MKGzCKjAyMfWRWV5QNJ:bvm7z8d) ([raw file](https://github.com/eastgenomics/eggd_athena/blob/ead5ac196948bd24fc2c6a2363948d729143f070/dxapp.json#L5)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Resolved
___
*[dxapp.json, line 42 at r1](https://reviewable.io/reviews/eastgenomics/eggd_athena/1#-MJl7AD93RsgVQ7Kopp7:-MKGzEtk8sLf9EXTdYpk:bvm7z8d) ([raw file](https://github.com/eastgenomics/eggd_athena/blob/ead5ac196948bd24fc2c6a2363948d729143f070/dxapp.json#L42)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Resolved
___
*[dxapp.json, line 100 at r1](https://reviewable.io/reviews/eastgenomics/eggd_athena/1#-MJl8M4QBWJ2xLes18u9:-MKGzMYnCSK9hobbVDu3:bvm7z8d) ([raw file](https://github.com/eastgenomics/eggd_athena/blob/ead5ac196948bd24fc2c6a2363948d729143f070/dxapp.json#L100)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Resolved
___
*[src/eggd_athena.sh, line 19 at r1](https://reviewable.io/reviews/eastgenomics/eggd_athena/1#-MJlAjVRBeVviM__KSzK:-MKGzNDG1WouG-uXg7KB:bvm7z8d) ([raw file](https://github.com/eastgenomics/eggd_athena/blob/ead5ac196948bd24fc2c6a2363948d729143f070/src/eggd_athena.sh#L19)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Resolved
___
*[src/eggd_athena.sh, line 41 at r1](https://reviewable.io/reviews/eastgenomics/eggd_athena/1#-MJlKeiaAyJHljGL5vw7:-MKGzNupDKtNJid1awRw:bvm7z8d) ([raw file](https://github.com/eastgenomics/eggd_athena/blob/ead5ac196948bd24fc2c6a2363948d729143f070/src/eggd_athena.sh#L41)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Resolved
___
*[src/eggd_athena.sh, line 53 at r1](https://reviewable.io/reviews/eastgenomics/eggd_athena/1#-MJlLmjn3jhZGloXnJ29:-MKGzOMiCQM6EFd7bpIC:bvm7z8d) ([raw file](https://github.com/eastgenomics/eggd_athena/blob/ead5ac196948bd24fc2c6a2363948d729143f070/src/eggd_athena.sh#L53)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Resolved
___
*[src/eggd_athena.sh, line 65 at r1](https://reviewable.io/reviews/eastgenomics/eggd_athena/1#-MJlMA63-N3v26awLzCl:-MKGzOlZ5O1EcEzNXzNC:bvm7z8d) ([raw file](https://github.com/eastgenomics/eggd_athena/blob/ead5ac196948bd24fc2c6a2363948d729143f070/src/eggd_athena.sh#L65)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Resolved
___
*[src/eggd_athena.sh, line 69 at r1](https://reviewable.io/reviews/eastgenomics/eggd_athena/1#-MJlMB4tA5wNehvDTyPf:-MKGzP5s30R7MWePJ8MI:bvm7z8d) ([raw file](https://github.com/eastgenomics/eggd_athena/blob/ead5ac196948bd24fc2c6a2363948d729143f070/src/eggd_athena.sh#L69)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Resolved
___
*[src/eggd_athena.sh, line 72 at r1](https://reviewable.io/reviews/eastgenomics/eggd_athena/1#-MJlMBd_1_2uqJlCFz1n:-MKGzPQA5MHvbA-S3CJr:bvm7z8d) ([raw file](https://github.com/eastgenomics/eggd_athena/blob/ead5ac196948bd24fc2c6a2363948d729143f070/src/eggd_athena.sh#L72)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Resolved
___
*[src/eggd_athena.sh, line 94 at r1](https://reviewable.io/reviews/eastgenomics/eggd_athena/1#-MJlMCxu007XWvd8uJfg:-MKGzPsXBtBF-DiwC0MH:bvm7z8d) ([raw file](https://github.com/eastgenomics/eggd_athena/blob/ead5ac196948bd24fc2c6a2363948d729143f070/src/eggd_athena.sh#L94)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Resolved

**Review by mattgarner — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_athena/1)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
