### PR TITLE
Bugfixes/issue 17

### PR DESCRIPTION
**Pull request by spaul91**
Bug in `per_chromosome_coverage` argument handling by the app. See issue #17.

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_athena/18)

### CODE REVIEW

**Comment by spaul91** [comment]
CAPA testing report: https://cuhbioinformatics.atlassian.net/wiki/spaces/UTILS/pages/2489614341/Athena+v1.3.0+eggd+athena+v1.3.0

Report with coverage: https://platform.dnanexus.com/panx/project-G6Pkb384qPGBfY9P6B33Qgxx/file-G6xbv6j4v16Gx1v021ZkfbJj/view?viewer=true

Report without coverage: https://platform.dnanexus.com/panx/project-G6Pkb384qPGBfY9P6B33Qgxx/file-G6xbq0Q4P50Xq7BQ275J01KV/view?viewer=true

**Review by spaul91 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_athena/18)* status: 0 of 2 files reviewed, 1 unresolved discussion

___
*[dxapp.json, line 7 at r1](https://reviewable.io/reviews/eastgenomics/eggd_athena/18#-Mr32Y-gEZYpwbTy38iD:-Mr32Y-h3oRL-4ChChTC:b7w0elx) ([raw file](https://github.com/eastgenomics/eggd_athena/blob/ed5b7e989d3c1c173c17b995cc67fb30b4d55b14/dxapp.json#L7)):*
> ```JSON
>   "dxapi": "1.0.0",
>   "billTo": "org-emee_1",
>   "version": "1.3.1",
> ```

Note: I haven't released v1.3.0 on github, so I can decrement this back to v1.3.0 if that's the right thing to do

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_athena/18)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @jethror1 and @spaul91)

___
*[src/eggd_athena.sh, line 105 at r1](https://reviewable.io/reviews/eastgenomics/eggd_athena/18#-Mr3A_Rw1FaiWRhEZZg4:-Mr3A_Rx5_s3Z1rBY3Qe:bl3f5p8) ([raw file](https://github.com/eastgenomics/eggd_athena/blob/ed5b7e989d3c1c173c17b995cc67fb30b4d55b14/src/eggd_athena.sh#L105)):*
> ```Shell
>         report_args+=" --snps $snp_vcfs";
>     fi
>     shopt -s nocasematch
> ```

is `shopt` required here? If it's just a boolean app input you're checking you can just do `[ "$per_chromosome_coverage" = true ]`

example: https://github.com/eastgenomics/eggd_conductor/blob/a52bca39cf77e562069c8997da4f44a5dc058f95/src/eggd_conductor.sh#L452

**Comment by spaul91** [comment]
___
*[src/eggd_athena.sh, line 105 at r1](https://reviewable.io/reviews/eastgenomics/eggd_athena/18#-Mr3A_Rw1FaiWRhEZZg4:-Mr6ov8n60fw47Wfo1BU:b-utud0) ([raw file](https://github.com/eastgenomics/eggd_athena/blob/ed5b7e989d3c1c173c17b995cc67fb30b4d55b14/src/eggd_athena.sh#L105)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

is `shopt` required here? If it's just a boolean app input you're checking you can just do `[ "$per_chromosome_coverage" = true ]`

example: https://github.com/eastgenomics/eggd_conductor/blob/a52bca39cf77e562069c8997da4f44a5dc058f95/src/eggd_conductor.sh#L452
</blockquote></details>

I wanted to account for cases where the user might submit "True", "TRUE" or "true" when launching from the CLI.

**Review by jethror1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_athena/18#-:-Mr7vGptCTd05fTf7hqI:bnfp4nl)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @jethror1)

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_athena/18)* status: all files reviewed, 1 unresolved discussion (waiting on @jethror1)

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_athena/18)* status: all files reviewed, 1 unresolved discussion (waiting on @spaul91)

___
*[dxapp.json, line 7 at r1](https://reviewable.io/reviews/eastgenomics/eggd_athena/18#-Mr32Y-gEZYpwbTy38iD:-Mr7w8_QAxHCoVsdMnQI:b32w0x) ([raw file](https://github.com/eastgenomics/eggd_athena/blob/ed5b7e989d3c1c173c17b995cc67fb30b4d55b14/dxapp.json#L7)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

Note: I haven't released v1.3.0 on github, so I can decrement this back to v1.3.0 if that's the right thing to do
</blockquote></details>

OK

**Review by jethror1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_athena/18#-:-Mr7wFb7EvTsUTRLNt9y:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @spaul91)

**Pull request merged**
