### PR TITLE
v1.4.0

### PR DESCRIPTION
**Pull request by jethror1**
- Adds Athena v1.4.1
  - ability to handle multiple transcripts, intronic regions and copy buttons to tables
- Bump app top Ubuntu 20, removes requirement for bundled miniconda3.8
- Switch packages for pybedtools, pandasql and retrying from source tars to pre-built wheels
  - reduces run time by ~1 minute
- Compress annotated bed file for output to reduce size by ~90%
- Change `exons_nirvana` input name to `exons_file`
- Example job: https://platform.dnanexus.com/projects/G9k5Pv04xYkg2X9j37K5BxQp/monitor

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_athena/20)

### CODE REVIEW

**Review by Yu-jinKim — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_athena/20)* status: 0 of 29 files reviewed, 1 unresolved discussion (waiting on @jethror1 and @Yu-jinKim)

___
*[`dxapp.json` line 33 at r1](https://reviewable.io/reviews/eastgenomics/eggd_athena/20#-N1Ik2E1BKb0tQTxmulL:-N1Ik2E1BKb0tQTxmulM:b9k8s2y) ([raw file](https://github.com/eastgenomics/eggd_athena/blob/412257a35043de2557d229ab3cc236233e294999/dxapp.json#L33)):*
> ```JSON
>     },
>     {
>       "name": "exons_file",
> ```

i thought about that while testing dias and i wonder if we should change this to be a CDS file since it's not exons in the file. Was that change discussed with Matt?

**Review by Yu-jinKim — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_athena/20)* status: 0 of 29 files reviewed, 2 unresolved discussions (waiting on @jethror1 and @Yu-jinKim)

___
*[`src/eggd_athena.sh` line 10 at r1](https://reviewable.io/reviews/eastgenomics/eggd_athena/20#-N1Il30sA3cf6-VB71Lo:-N1Il30sA3cf6-VB71Lp:b-qnonrj) ([raw file](https://github.com/eastgenomics/eggd_athena/blob/412257a35043de2557d229ab3cc236233e294999/src/eggd_athena.sh#L10)):*
> ```Shell
>     # download inputs
>     dx download "$panel_bed"
>     dx download "$exons_file"
> ```

see the comment in the dxapp.json

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_athena/20)* status: 0 of 29 files reviewed, 2 unresolved discussions (waiting on @Yu-jinKim)

___
*[`dxapp.json` line 33 at r1](https://reviewable.io/reviews/eastgenomics/eggd_athena/20#-N1Ik2E1BKb0tQTxmulL:-N1InNC08GcKvEFymG3P:bbwidw3) ([raw file](https://github.com/eastgenomics/eggd_athena/blob/412257a35043de2557d229ab3cc236233e294999/dxapp.json#L33)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

i thought about that while testing dias and i wonder if we should change this to be a CDS file since it's not exons in the file. Was that change discussed with Matt? 
</blockquote></details>

for this I'm just changing the name of the input since it seemed wrong to call it nirvana as we've made an equivalent for Uranus from cellbase for some transcripts. I don't want to change the structure of the file for this release since we need it done for next week, but can consider for future
___
*[`src/eggd_athena.sh` line 10 at r1](https://reviewable.io/reviews/eastgenomics/eggd_athena/20#-N1Il30sA3cf6-VB71Lo:-N1Io7CaAmnz-qeErdqG:byr4ffv) ([raw file](https://github.com/eastgenomics/eggd_athena/blob/412257a35043de2557d229ab3cc236233e294999/src/eggd_athena.sh#L10)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

see the comment in the dxapp.json
</blockquote></details>

see above

**Review by Yu-jinKim — APPROVED** [review]
> Reviewed 25 of 29 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_athena/20)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jethror1)

**Pull request merged**
